---
- name: Gather Cisco IOS Facts
  hosts: "{{ _hosts | default(ansible_limit) | default('ios') }}"
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Gather all available facts from Cisco IOS devices
      cisco.ios.ios_facts:
        gather_subset: all
        gather_network_resources: all
      register: ios_facts_result

    - name: Display system information
      ansible.builtin.debug:
        msg: "{{ system_info | to_nice_json }}"
      vars:
        system_info:
          hostname: "{{ ansible_net_hostname | default('N/A') }}"
          model: "{{ ansible_net_model | default('N/A') }}"
          serial_number: "{{ ansible_net_serialnum | default('N/A') }}"
          ios_version: "{{ ansible_net_version | default('N/A') }}"
          ios_type: "{{ ansible_net_iostype | default('N/A') }}"
          image: "{{ ansible_net_image | default('N/A') }}"
          system: "{{ ansible_net_system | default('N/A') }}"

    - name: Display hardware details
      ansible.builtin.debug:
        msg: "{{ hardware_info | to_nice_json }}"
      vars:
        hardware_info:
          stacked_masters: "{{ ansible_net_stacked_masters | default([]) }}"
          stacked_serialnums: "{{ ansible_net_stacked_serialnums | default([]) }}"
          filesystems: "{{ ansible_net_filesystems | default([]) }}"
          filesystems_info: "{{ ansible_net_filesystems_info | default({}) }}"
          memory_free_mb: "{{ ansible_net_memfree_mb | default('N/A') }}"
          memory_total_mb: "{{ ansible_net_memtotal_mb | default('N/A') }}"

    - name: Display interface information
      ansible.builtin.debug:
        msg: "{{ interface_info | to_nice_json }}"
      vars:
        interface_info:
          ipv4_addresses: "{{ ansible_net_all_ipv4_addresses | default([]) }}"
          ipv6_addresses: "{{ ansible_net_all_ipv6_addresses | default([]) }}"
          interfaces: "{{ ansible_net_interfaces | default({}) }}"

    - name: Display neighbors (CDP/LLDP)
      ansible.builtin.debug:
        msg: "{{ ansible_net_neighbors | default({}) | to_nice_json }}"

    - name: Display network resources
      ansible.builtin.debug:
        msg: "{{ ansible_network_resources | default({}) | to_nice_json }}"

    - name: Display all gathered facts
      ansible.builtin.debug:
        msg: "{{ ios_facts_result.ansible_facts | to_nice_json }}"
      tags: raw_facts
      when: show_raw_facts | default(false) | bool

    - name: Save facts to file
      delegate_to: localhost
      ansible.builtin.copy:
        content: "{{ ios_facts_result.ansible_facts | to_nice_json }}"
        dest: "facts/{{ inventory_hostname }}_facts.json"
        mode: '0644'
      tags: save_facts
      when: save_facts | default(false) | bool
